### ISSUE TITLE
Enum names colliding with MSVC typedefs

### ISSUE THREAD

**Issue by wiired24** [adam-becker/psxact#11]
Inside of your bus.hpp file you set up an enumeration for {BYTE,WORD,HALF}
Correct me if I am mistaken but It would seem as if these are types?
The compiler keeps yelling at me saying "WORD: Illegal use of this "type" as an expression and i get 30+ errors all related to basically the exact same problem.
It also will give me the same error for BYTE too as  it is being used by bus::write or similar functions.  

One fix would be instead of 

Enum {
BYTE
WORD
HALF
}

do 

Enum {

BYTE_b
Word_w
HALF_h

}

And then whenever you need to use your enums when working with expressions or functions just do it like this

auto data = read_data(bus::HALF_h, address);

**Comment by adam-becker** [comment]
Use the fully qualified names:

- `bus_width_t::BYTE`
- `bus_width_t::HALF`
- `bus_width_t::WORD`

Enums in C/C++ are annoying since they pollute the enclosing context. I'll rename the members later as:

```c
enum bus_width_t {
  BUS_WIDTH_BYTE,
  BUS_WIDTH_HALF,
  BUS_WIDTH_WORD
};
```

I believe the names are clashing with the MSVC typedefs of `BYTE` for `unsigned char`, etc. I typically only compile PSXACT with clang++ and/or g++.

**Comment by wiired24** [comment]
Yeah MSVC is weird lol
Okay Will do Thank you for the info on that.
