### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by Thunder07** [adam-becker/psxact#16]
I can confirm this does build on OSX, I just had to replace `FindSDL2.cmake` with the one you linked to.

why haven't you replaced the one here with that?

**Comment by adam-becker** [comment]
Good question. I bundled the `FindSDL2.cmake` because I started having issues with the one linked in the README, and never got around to update the README.

The bundled script just allows you to directly set the paths when you know where SDL2 is installed on your system, instead of letting a magic process work it out behind the scenes. The README should probably be updated at some point with current build instructions.

**Comment by Thunder07** [comment]
haha it's that magic process that makes cmake the go to build system.

anyway, from what I understood, your issue was with VS 2017 (aka windows) and the linked `FindSDL2.cmake` doesn't even try to find sdl2 on windows... for obvious reasons (windows doesn't have a standard header or library directory), however, if you look at [this](https://github.com/tcbrindle/sdl2-cmake-scripts/blob/master/FindSDL2.cmake#L79) line, you'd see they already allow you to specific sdl2 directory and let the script handle the rest.

**Comment by adam-becker** [comment]
I think my rationale at the time was that it seemed simpler to put the path directly into a CMake module file since they are user-specific anyways.

Bundled CMake module = 1 module, 0 environment variables
Linked CMake module = 1 module, 1 environment variable

The bundled module doesn't have any paths in it, instead it directs users to fill that in themselves. But as I said, the README should be updated (And windows builds should be settled also). I mostly build/develop PSXACT on Debian, so I don't get around to trying it on Windows much.

**Comment by Thunder07** [comment]
`/usr/local/include/SDL2/`

why does it sound you're still trying to hard code these in :?

I'll see if i can get you a probably working PR for all of OSX/Win/Linux later tonight.

**Comment by adam-becker** [comment]
I ask because Ubuntu seems to expect your includes to be `#include <SDL2/SDL.h>`, so I was wondering if it's the same for OSX.

I remember reading somewhere that it's proper to do `#include <SDL.h>`, but that appears to be incorrect?

**Comment by Thunder07** [comment]
thats also true for OSX, technically my answer should have been `/usr/local/include` which would mean this is the correct include `#include <SDL2/SDL.h>`.

but back to the `FindSDL2.cmake` [line 85](https://github.com/tcbrindle/sdl2-cmake-scripts/blob/master/FindSDL2.cmake#L85) which searches `/usr/local/` + `include/SDL2` making `#include <SDL.h>` the correct header.

**Comment by adam-becker** [comment]
I've tested with Ubuntu and Debian (Basically the same, so not a very thorough test) and both expect you to do `#include <SDL2/SDL.h>` when using the linked `FindSDL2.cmake` module.

It seems to be standard, and I guess it would make sense. Allowing `SDL2` to be SxS compatible with `SDL` and all.

I may have to tailor the module a little if it's causing different systems to expect different include paths for `SDL2`.

**Comment by Thunder07** [comment]
`FindSDL2.cmake` is not being loaded, you're missing this line.

```
set(CMAKE_MODULE_PATH
	${CMAKE_CURRENT_SOURCE_DIR}/modules
	${CMAKE_MODULE_PATH}
)
```

as such, Ubuntu/cmake checks the default include directory `/usr/local/include` thus it expects the header to be in `SDL2/SDL.h`

**Comment by adam-becker** [comment]
On my Debian machine I had moved the `FindSDL2.cmake` module directly into `${CMAKE_MODULE_PATH}` so it gets resolved. I'm probably just making a very minor error at some point in the build process and causing confusion :smile: I'll wait and see what you come up with.
