### ISSUE TITLE
bus.hpp redefinition error

### ISSUE THREAD

**Issue by wiired24** [adam-becker/psxact#9]
Just wanted to let you know that inside of your bus.hpp header file

You have your Enum {BYTE,WORD,HALF}  outside of the bus namespace. This could result in a redefinition error.

**Comment by adam-becker** [comment]
Thank you. I had a look at your psx-box repo and noticed a surprising amount of this emulator's code in it. What are your plans for psx-box?

**Comment by wiired24** [comment]
Well, First thank you for writing psxact
Me and a few other guys are attempting to create a PS1 Emulator for the
Xbox One that can be sideloaded in (Developer Mode)
Currently the only port out there  is very unstable and doesn't run any
games. I understand that your emulator can't boot any commercial games yet
either but it looks like your making steady progress on it to be honest. I
have worked with C++ before but I'm new to working with developing UWP
Applications so getting the UI right for Xbox One is going to be a big
challenge haha. If i find any more errors I will definitely let you know.
I'm want to try to help psxact be the best emulator it can be in any way I
can because if your emulator is solid then in turn so is psx-box

**Comment by adam-becker** [comment]
Okay, that all sounds fine. Thank you also for giving credit in your Authors.txt file!

However, since this is basically a custom front-end you're building I do have some ideas for how it should be structured so that both of our projects can exist side-by-side and flourish.

- Consider adding this repository as a [submodule](https://git-scm.com/docs/git-submodule) in your repository.

This has some benefits, including making your code easier to sync with this repository. It also keeps the development of the PSXACT core in a single place.

- Consider a proper fork of this repository instead of copy/pasting.

This is how GPL projects work for the most part, satisfying that changes made to the original are made available. It's also more in line with the spirit of collaboration that GitHub tries to foster.

I am very open to pull requests, and helping in any way I can to make sure that PSXACT is the best PSX emulator available, I just fear that the way your project is structured will stifle productivity in the long run.

Also as a side note, I think your project must use GPL-3.0 since it's based off of my code which is also GPL-3.0

I'm also not against having multiple front-ends available in this repository, if you would like to combine efforts? Just a thought :smile:

**Comment by wiired24** [comment]
Your Welcome, I mean you have done alot of work on psx-act I felt it was only fair to credit you.

Also, Thanks for the feedback. I will add it as a submodule here in a bit. And yeah I was thinking that I would probably need to change the license to GPL Version 3  since that's what psxact uses but I was unsure.

**Comment by adam-becker** [comment]
It may also be good to treat PSXACT as a third-party library, like SDL. I could tailor the code more towards that use case, and make it easier to consume PSXACT as a library. I think I would have to provide a header file with a simple interface, like a single `cycle` function to advance the emulation. What are your thoughts? How do you plan on using PSXACT going forward?

**Comment by wiired24** [comment]
Yeah That way I could easily just include it as a library. It would pretty much work as a dependency just like SDL etc I really like that idea. That way I could have just all of the UI Code in one single place and pull psxact in as sort of a backend.  Btw I already updated the License to GPLv3 I'll be adding psx-box as a submodule soon.
